### ISSUE TITLE
Migrate all QE LEM lab automation to rpc-gating

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-gating#27]
QE needs to migrate all our lab automation code to rpc-gating to ensure that we use the same JJB code to deploy

**Comment by jacobwagner** [comment]
Managed to move all pertinent ansible automation code to the new repo. Will make a PR once it is all finalized.

**Comment by mattt416** [comment]
Thanks @jacobwagner!  Do you want to create this issue under u-suk-dev so we can track it on waffle?

**Comment by jacobwagner** [comment]
I did. I might close this one and just track it there
